---
title: "data_analysis"
author: "Wesley Janson, Drew Keller, Sergio Olalla, Michael Wagner"
date: "2023-02-07"
output: pdf_document
---

```{r (Load packages and data), echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(tseries)
library(forecast)
library(TSA)
library(MLmetrics)
setwd("/Users/wrjanson/Documents/UChicago/Time Series/chicago_rental_index") # Need to think of the general way to set this up
```

```{r}
full_data <- read.csv("raw_data.csv")
full_data <- ts(full_data$index_value, start = c(1979,1), frequency=12)

# Train/Test Split
train_data <- window(full_data, end=c(2014,12))
test_data <- window(full_data, start=c(2015,1), end=c(2022,12))

tsdisplay(train_data, main = "Training Data")
tsdisplay(test_data, main = "Testing Data")
```

## Box-Cox Transformation??
```{r}
opt_lambda <- BoxCox.lambda(train_data)
cat(paste0("Optimal lambda value: ", opt_lambda))
```


## Seasonally Difference??
```{r}

```



## Is there a trend (haha)??
```{r}
kpss.test(train_data)
kpss.test(diff(train_data))

tsdisplay(diff(train_data))
```


## What does EACF function say?
```{r}
eacf(diff(train_data))
```

## What about auto.arima()?
```{r}
opt_model_no_season <- auto.arima(train_data, lambda = opt_lambda, seasonal = FALSE)
opt_model_no_season

opt_model_with_season <- auto.arima(train_data, lambda = opt_lambda, seasonal = TRUE)
opt_model_with_season
```


```{r (Forecasting)}
mod_for <- forecast(opt_model_with_season, h=length(test_data))$mean

accuracy(mod_for, test_data)

autoplot(full_data, main = "Forecast", ylab="") + 
  autolayer(mod_for)
```



