---
title: "Rent and Inventory SARIMA and ETS"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(tseries)
library(forecast)
library(TSA)
library(dplyr)
```

### Load and inspect data

```{r}
# source: https://streeteasy.com/blog/data-dashboard/?agg=Total&metric=Inventory&type=Rentals&bedrooms=Any%20Bedrooms&property=Any%20Property%20Type&minDate=2010-01-01&maxDate=2022-12-01&area=Flatiron,Brooklyn%20Heights

# note that we can also get breakdown by bedrooms if we want

# set up generalizable path without local path hard coded
base_path <- system('git rev-parse --show-toplevel', intern = T)

# rental index - one for each of four real boroughs
rental_index_raw <- read.csv(paste0(base_path, '/data/rentalIndex_All.csv'))
# median asking rent - four real boroughs + 155 neighborhoods
median_rent_raw <- read.csv(paste0(base_path, '/data/medianAskingRent_All.csv'))
# rental inventory - four real boroughs + 155 neighborhoods
inventory_raw <- read.csv(paste0(base_path, '/data/rentalInventory_All.csv'))

```

```{r}
rental_index_manhattan <- ts(rental_index_raw$Manhattan,
                             start=c(2007,1),
                             frequency=12)

tsdisplay(rental_index_manhattan)

median_rent_manhattan <- median_rent_raw %>% 
  filter(areaName=="Manhattan") %>%
  unlist() %>% as.numeric() %>% 
  na.omit() %>% 
  ts(start=c(2010,1),frequency=12)

tsdisplay(median_rent_manhattan)

inventory_manhattan <- inventory_raw %>% 
  filter(areaName=="Manhattan") %>% 
  unlist() %>% as.numeric() %>% 
  na.omit() %>%
  ts(start=c(2010,1),frequency=12)

tsdisplay(inventory_manhattan)

rent_train <- window(median_rent_manhattan, start=2010, end=c(2020,1))
inventory_train <- window(inventory_manhattan, start=2010, end=c(2020,1))
rent_test <- window(median_rent_manhattan, start=c(2020,2), end=c(2022,12))
inventory_test <- window(inventory_manhattan, start=c(2020,2), end=c(2022,12))

# Box-Cox transformed
tsdisplay(BoxCox(rent_train,lambda='auto'))
tsdisplay(BoxCox(inventory_train,lambda='auto'))
```

```{r}
#save(inventory_manhattan,file='data/inventory_manhattan.RData')
#save(median_rent_manhattan,file='data/median_rent_manhattan.RData')
```

### SARIMA

```{r}
# we won't use the rental index as it appears to be smoothed
# median rent SARIMA
rent_sarima <- auto.arima(rent_train,lambda='auto',trace=TRUE)
checkresiduals(rent_sarima)
```


```{r}
boxcox_inventory_sarima <- auto.arima(inventory_train,max.d=1,lambda='auto')
checkresiduals(boxcox_inventory_sarima)
inventory_sarima <- auto.arima(inventory_train,lambda=NULL,trace=TRUE)
checkresiduals(inventory_sarima)
```

### ETS

```{r}
# don't force lambda, because that forces additive model

rent_ets <- ets(median_rent_manhattan)
summary(rent_ets)
checkresiduals(rent_ets)

inventory_ets <- ets(inventory_manhattan)
summary(inventory_ets)
checkresiduals(inventory_ets)
```


### Cross-validation

```{r}
### cross-validation helper functions

add_NAs_to_list <- function(lst) {
  n <- length(lst)
  if (n >= 12) {
    return(lst)
  }
  return(c(lst, rep(NA, 12 - n)))
}

rent_SARIMA_model = function(training_data){
  return(Arima(
    training_data,order=c(2,1,1),seasonal=c(2,0,1),
    include.drift=TRUE,lambda="auto",method='CSS-ML'))}

inventory_SARIMA_model = function(training_data){
  return(Arima(
    training_data,order=c(1,1,0),seasonal=c(2,0,0),method='CSS-ML'))}

rent_ets_model = function(training_data){
  return(ets(training_data,model="MAN"))}

inventory_ets_model = function(training_data){
  return(ets(training_data,model="MAA"))}

predict_and_forecast = function(model,series,i,last_training_point,n_forecast,window_type){
  if (window_type=="expanding"){
    training_window <- ts(series[1:last_training_point],frequency=12)
  } else if (window_type=="sliding"){
    training_window <- ts(series[i:last_training_point],frequency=12)}
  last_test_point <- ifelse(
    last_training_point+n_forecast<=length(series),
    last_training_point+n_forecast,
    length(series))
  true_future <- series[(last_training_point+1):(last_training_point+n_forecast)]
  model_trained <- model(training_window)
  model_aicc <- model_trained$aicc
  forecast_error <- forecast(model_trained,h=length(true_future))$mean-true_future 
  return(list(model_aicc,add_NAs_to_list(forecast_error)))
}

# cross-validation function
cross.validate = function(model,series,n_window,n_forecast){

  # initialize
  iterations <- length(series)-n_window
  model_aicc_expanding <- vector(mode='list', length=iterations)
  error_expanding <- vector(mode='list', length=iterations)
  model_aicc_sliding <- vector(mode='list', length=iterations)
  error_sliding <- vector(mode='list', length=iterations)

  # expanding
  for (i in 1:iterations){
    iteration_output <- predict_and_forecast(model,series,i,i+n_window-1,n_forecast,"expanding")
    model_aicc_expanding[i] <- iteration_output[1]
    error_expanding[[i]] <- iteration_output[2]
  }
  
  # sliding
  for (i in 1:iterations){
    iteration_output <- predict_and_forecast(model,series,i,i+n_window-1,n_forecast,"sliding")
    model_aicc_sliding[i] <- iteration_output[1]
    error_sliding[[i]] <- iteration_output[2]
  } 
  
  return(list(model_aicc_expanding,error_expanding,model_aicc_sliding,error_sliding))
}
```

```{r}
# predict
output_rent_arima <- cross.validate(rent_SARIMA_model,median_rent_manhattan,78,12)
output_rent_ets <- cross.validate(rent_ets_model,median_rent_manhattan,78,12)
```

