---
title: "VAR"
output: html_notebook
---

```{r}
# rm(list=ls())
library(tidyverse)
library(tseries)
library(forecast)
library(TSA)
library(dplyr)
library(vars)
library(fpp)
library(tseries)
library(rlist)
library(tseries)
library(TSA)
library(readxl)
library(lubridate)
library(ggfortify)
library(Metrics)
library(ggplot2)
```

### Helper function
```{r (Untransform/undifference function for forecasts)}

backout <- function(input_data, original_series, lambda_val, diff_num, lag_num) {
  box_cox_orig <- BoxCox(original_series, lambda = lambda_val)

  # Undo differencing and BoxCox:
  undifferenced <- diffinv(input_data, differences = diff_num, lag=lag_num, xi=box_cox_orig[length(original_series)])
  
  
  output_data <- InvBoxCox(undifferenced, lambda = lambda_val)
  
  return(output_data)
}
```


### Load and inspect data
```{r}
# source: https://streeteasy.com/blog/data-dashboard/?agg=Total&metric=Inventory&type=Rentals&bedrooms=Any%20Bedrooms&property=Any%20Property%20Type&minDate=2010-01-01&maxDate=2022-12-01&area=Flatiron,Brooklyn%20Heights

# note that we can also get breakdown by bedrooms if we want

# set up generalizable path without local path hard coded
base_path <- system('git rev-parse --show-toplevel', intern = T)

# rental index - one for each of four real boroughs
rental_index_raw <- read.csv(paste0(base_path, '/data/rentalIndex_All.csv'))
# median asking rent - four real boroughs + 155 neighborhoods
median_rent_raw <- read.csv(paste0(base_path, '/data/medianAskingRent_All.csv'))
# rental inventory - four real boroughs + 155 neighborhoods
inventory_raw <- read.csv(paste0(base_path, '/data/rentalInventory_All.csv'))

```

```{r}
rental_index_manhattan <- ts(rental_index_raw$Manhattan,
                             start=c(2007,1),
                             frequency=12)

tsdisplay(rental_index_manhattan)

median_rent_manhattan <- median_rent_raw %>% 
  filter(areaName=="Manhattan") %>%
  unlist() %>% as.numeric() %>% 
  na.omit() %>% 
  ts(start=c(2010,1),frequency=12)

tsdisplay(median_rent_manhattan)

inventory_manhattan <- inventory_raw %>% 
  filter(areaName=="Manhattan") %>% 
  unlist() %>% as.numeric() %>% 
  na.omit() %>%
  ts(start=c(2010,1),frequency=12)

tsdisplay(inventory_manhattan)

#save(inventory_manhattan,file='data/inventory_manhattan.RData')
#save(median_rent_manhattan,file='data/median_rent_manhattan.RData')
sales_days_raw <- read.csv(paste0(base_path, '/data/Sales/daysOnMarket_All.csv'))
sales_price_raw <- read.csv(paste0(base_path, '/data/Sales/medianSalesPrice_All.csv'))

sales_days_manhattan <- sales_days_raw  %>% 
  filter(areaName=="Manhattan") %>%
  unlist() %>% as.numeric() %>% 
  na.omit() %>% 
  ts(start=c(2010,1),frequency=12)

tsdisplay(sales_days_manhattan)

sales_price_manhattan <- sales_price_raw %>% 
  filter(areaName=="Manhattan") %>% 
  unlist() %>% as.numeric() %>% 
  na.omit() %>%
  ts(start=c(2010,1),frequency=12)

tsdisplay(sales_price_manhattan)

##### Training Data
rent_train <- window(median_rent_manhattan, start=2010, end=c(2020,1))
inventory_train <- window(inventory_manhattan, start=2010, end=c(2020,1))
sales_days_train <- window(sales_days_manhattan, start=2010, end=c(2020,1))
sales_price_train <- window(sales_price_manhattan, start=2010, end=c(2020,1))

##### Testing Data
rent_test <- window(median_rent_manhattan, start=c(2020,2), end=c(2022,12))
inventory_test <- window(inventory_manhattan, start=c(2020,2), end=c(2022,12))
sales_days_test <- window(sales_days_manhattan, start=c(2020,2), end=c(2022,12))
sales_price_test <- window(sales_price_manhattan, start=c(2020,2), end=c(2022,12))

# Box-Cox transformed
lambda_rent <- BoxCox.lambda(rent_train)
lambda_inventory <- BoxCox.lambda(inventory_train)
lambda_sales_days <- BoxCox.lambda(sales_days_train)
lambda_sales_price <- BoxCox.lambda(sales_price_train)

# Plot transformed data
tsdisplay(BoxCox(rent_train, lambda=lambda_rent))
tsdisplay(BoxCox(inventory_train,lambda=lambda_rent))
tsdisplay(BoxCox(inventory_train,lambda=0))
tsdisplay(BoxCox(sales_days_train,lambda=lambda_sales_days))
tsdisplay(BoxCox(sales_price_train,lambda=lambda_sales_price))
```

```{r (Check for Stationarity)}
kpss.test(BoxCox(rent_train,lambda=lambda_rent))
kpss.test(BoxCox(inventory_train,lambda=lambda_rent))
kpss.test(BoxCox(sales_days_train,lambda=lambda_rent))
kpss.test(BoxCox(sales_price_train,lambda=lambda_rent))

kpss.test(diff(BoxCox(rent_train,lambda=lambda_rent), differences=1,lag=1))
kpss.test(diff(BoxCox(inventory_train,lambda=lambda_rent), differences=1,lag=1))
kpss.test(diff(BoxCox(sales_days_train,lambda=lambda_rent), differences=1,lag=1))
kpss.test(diff(BoxCox(sales_price_train,lambda=lambda_rent), differences=1,lag=1))
```


# VAR

### Inventory
```{r}
# VAR Selection
data_stationary <- cbind(diff(BoxCox(rent_train, lambda = lambda_rent), differences = 1), diff(BoxCox(inventory_train, lambda=0), differences = 1))

VARselect(data_stationary, lag.max=12)$selection

inventory_var <- VAR(data_stationary, p=5, type='both', season=12)
summary(inventory_var)

## Create forecast
var1_forecast <- forecast(inventory_var, h=length(rent_test))$forecast

# Plot of Median Rent
plot(backout(var1_forecast$diff.BoxCox.rent_train..lambda...lambda_rent...differences...1.$mean, rent_train, lambda_rent, 1, 1), ylab="Median Rent")

# Plot of Inventory
plot(backout(var1_forecast$diff.BoxCox.inventory_train..lambda...0...differences...1.$mean, inventory_train, 0, 1, 1), ylab="Inventory")

```


### BOTH White noise!!!!
```{r (Check residuals)}
checkresiduals(residuals(inventory_var)[,1], test=FALSE)
Box.test(residuals(inventory_var)[,1], type = c("Ljung-Box"))

checkresiduals(residuals(inventory_var)[,2], test=FALSE)
Box.test(residuals(inventory_var)[,2], type = c("Ljung-Box"))
```

### More plots
```{r (Forecast Plots)}
# Median Rent Plot
rent_forecast <- backout(var1_forecast$diff.BoxCox.rent_train..lambda...lambda_rent...differences...1.$mean, rent_train, lambda_rent, 1, 1)
autoplot(median_rent_manhattan, main = "Forecast for Median Rent", ylab="Median Rent") + 
  autolayer(rent_forecast)

# Inventory Plot
inventory_forecast <- backout(var1_forecast$diff.BoxCox.inventory_train..lambda...0...differences...1.$mean, inventory_train, 0, 1, 1)
autoplot(inventory_manhattan, main = "Forecast for Inventory", ylab="Inventory") + 
  autolayer(inventory_forecast)
```



### Cross Validation
```{r (Cross Validation)}
rmse_exp <- c()
rmse_sl <- c()

for (i in 1:floor(length(inventory_train) * 0.25)){

  n_sliding <- ceiling(length(inventory_train) * 0.75)
  
  expand_window_inv <- ts(inventory_train[1:(n_sliding + i)],frequency=12)
  sliding_window_inv <-  ts(inventory_train[i:n_sliding],frequency=12)
  
  expand_window_rent <- ts(rent_train[1:(n_sliding + i)],frequency=12)
  sliding_window_rent <-  ts(rent_train[i:n_sliding],frequency=12)
  
  test_rent <- ts(rent_train[(n_sliding + i): (n_sliding + i + 11)],frequency=12)
  test_inv <- ts(inventory_train[(n_sliding + i): (n_sliding + i + 11)],frequency=12)
  
  
    # VAR Selection
  data_stationary_exp <- cbind(diff(BoxCox(expand_window_rent, lambda = lambda_rent), differences = 1), diff(BoxCox(expand_window_inv, lambda=0), differences = 1))
  
    data_stationary_sl <- cbind(diff(BoxCox(sliding_window_rent, lambda = lambda_rent), differences = 1), diff(BoxCox(sliding_window_inv, lambda=0), differences = 1))
  
  
  inventory_var_exp <- VAR(data_stationary_exp, p=5, type='both', season=12)
  inventory_var_sl <- VAR(data_stationary_sl, p=5, type='both', season=12)
  
  ## Create forecast
  var_forecast_exp <- forecast(inventory_var_exp, h=length(test_rent))$forecast
  var_forecast_sl <- forecast(inventory_var_sl, h=length(test_rent))$forecast
  
  pred_rent_exp <- var_forecast_exp$diff.BoxCox.expand_window_rent..lambda...lambda_rent...differences...1.$mean
  pred_rent_sl <- var_forecast_sl$diff.BoxCox.sliding_window_rent..lambda...lambda_rent...differences...1.$mean
  
  pred_rent_exp <- ts(pred_rent_exp, frequency=12)
  pred_rent_sl <- ts(pred_rent_sl, frequency=12)
  
  pred_exp_rent <- backout(pred_rent_exp, expand_window_rent, lambda_rent, 1, 1)
  pred_sl_rent <- backout(pred_rent_sl, sliding_window_rent, lambda_rent, 1, 1)
  
  df <-  data.frame(pred_exp_rent[-1], test_rent)
  df <- na.omit(df)
  
  rmse_sl <- append(rmse_sl, rmse(df[,1], df[,2]))
  rmse_exp <- append(rmse_exp, rmse(df[,1], df[,2]))
  }
```

```{r}
x <- 1:floor(length(inventory_train) * 0.25)
```










# DON'T MESS WITH CODE BELOW


### Days for Sale
```{r}
VARselect(cbind(diff(BoxCox(rent_train, lambda = lambda_rent), differences = 1, lag=1), diff(BoxCox(sales_days_train,lambda=lambda_rent),differences=1,lag=1)), lag.max=12)$selection

days_var <- VAR(cbind(diff(BoxCox(rent_train, lambda = lambda_rent), differences = 1, lag=1), diff(BoxCox(sales_days_train,lambda=lambda_rent),differences=1,lag=1)), p=4, type='both', season=12)
summary(days_var)
```



```{r}
prices_sales_var <- VAR(cbind(median_rent_manhattan, sales_price_manhattan), p=10, type='both', season=12)
summary(prices_sales_var)
```


### Mortgages
```{r}
mortgage_raw  <- read.csv(paste0(base_path, '/data/MORTGAGE30US.csv'))
mortgage <- ts(mortgage_raw$MORTGAGE30US, start=c(2010,1),frequency=12)

tsdisplay(mortgage)

```
days_var <- VAR(cbind(median_rent_manhattan, sales_days_manhattan), p=10, type='both', season=12)





```{r}

box_cox_inv[length(inventory_train)]


inventory_train
box_cox_inv <- BoxCox(inventory_train, lambda = 0)
box_cox_inv_diff <- diff(box_cox_inv, differences=1, lag=1)

# Trying to undo this:
box_cox_inv2 <- diffinv(box_cox_inv_diff, differences=1, lag=1, xi=box_cox_inv[1])
plot(InvBoxCox(box_cox_inv2, lambda = 0))

plot(inventory_train)

```







```{r}

rent_train
box_cox_rent <- BoxCox(rent_train, lambda = lambda_rent)
box_cox_rent_diff <- diff(box_cox_rent, differences=1, lag=1)

# Trying to undo this:
box_cox_rent2 <- diffinv(box_cox_rent_diff, differences=1, lag=1, xi=box_cox_rent[1])
InvBoxCox(box_cox_rent2, lambda = lambda_rent)
```

