---
title: "VARIMA Analysis"
author: "Wesley Janson"
date: "2023-02-18"
output:
  pdf_document: default
  html_document: default
---

```{r (Load packages), echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(tseries)
library(forecast)
library(TSA)
library(dplyr)
library(MTS)
```

### Load and inspect data

```{r}
# source: https://streeteasy.com/blog/data-dashboard/?agg=Total&metric=Inventory&type=Rentals&bedrooms=Any%20Bedrooms&property=Any%20Property%20Type&minDate=2010-01-01&maxDate=2022-12-01&area=Flatiron,Brooklyn%20Heights

# set up generalizable path without local path hard coded
base_path <- system('git rev-parse --show-toplevel', intern = T)

# median asking rent - four real boroughs + 155 neighborhoods
median_rent_raw <- read.csv(paste0(base_path, '/data/medianAskingRent_All.csv'))
# rental inventory - four real boroughs + 155 neighborhoods
inventory_raw <- read.csv(paste0(base_path, '/data/rentalInventory_All.csv'))
```

```{r}
median_rent_manhattan <- median_rent_raw %>% 
  filter(areaName=="Manhattan") %>%
  unlist() %>% as.numeric() %>% 
  na.omit() %>% 
  ts(start=c(2010,1), frequency=12)

tsdisplay(median_rent_manhattan)

inventory_manhattan <- inventory_raw %>% 
  filter(areaName=="Manhattan") %>% 
  unlist() %>% as.numeric() %>% 
  na.omit() %>%
  ts(start=c(2010,1), frequency=12)

tsdisplay(inventory_manhattan)

rent_train <- window(median_rent_manhattan, start=2010, end=c(2020,1))
inventory_train <- window(inventory_manhattan, start=2010, end=c(2020,1))
rent_test <- window(median_rent_manhattan, start=c(2020,2), end=c(2022,12))
inventory_test <- window(inventory_manhattan, start=c(2020,2), end=c(2022,12))
```

```{r (BoxCox and Correlation Check)}
# Box-Cox transformed
lambda_rent <- BoxCox.lambda(rent_train)
lambda_inventory <- BoxCox.lambda(inventory_train)
tsdisplay(BoxCox(rent_train,lambda='auto'))
tsdisplay(BoxCox(inventory_train,lambda=0))

# Correlation
cor(rent_train, inventory_train)
cor(BoxCox(rent_train,lambda='auto'), BoxCox(inventory_train,lambda=0))
# Cross Correlations
ccf(inventory_train, rent_train, lag.max = 12)
ccf(BoxCox(inventory_train,lambda='auto'), BoxCox(rent_train,lambda=0), lag.max = 12)
```


## IGNORE
```{r (Testing for Stationarity)}
# data <- as.data.frame(cbind(rent_train, inventory_train))

# diff_function <- function(in_data) {
#   for (colm in 1:ncol(in_data)) {
#     i <- ts(in_data[,colm], start=c(2010,1), frequency=12)
#     lambda_i <- BoxCox.lambda(i)
#     print(paste0("Optimal lambda for ", colnames(data)[colm], " is ",lambda_i))
#     if (kpss.test(BoxCox(i, lambda = lambda_i))$p.value<0.05) {
#       if (kpss.test(diff(BoxCox(i, lambda = lambda_i), lag=12))$p.value<0.05) {
#         if (kpss.test(diff(BoxCox(i, lambda = lambda_i), diff=1, lag=12))$p.value<0.05) {
#           print("This data is fucked")
#         } else {
#           print(paste0("Variable ", colnames(data)[colm], " is stationary after seasonal differencing and first-order differencing"))
#         }
#       } else {
#         print(paste0("Variable ", colnames(data)[colm], " is stationary after seasonal differencing"))
#       }
#     } else {
#       print(paste0("Variable ", colnames(data)[colm], " does not need differencing"))
#     }
#   }
# }
#   
# diff_function(data)
```

```{r}
data <- as.data.frame(cbind(rent_train, inventory_train))
# a single nonseasonal difference is sufficient to make the inventory_train stationary:
kpss.test(diff(BoxCox(data$inventory_train,lambda='auto'),differences=1,lag=1),null='Level')
# this also works following 1 nonseasonal difference, though not as well (note: this is also what auto.arima finds):
kpss.test(diff(BoxCox(data$inventory_train,lambda=0),differences=1,lag=1),null='Level')
```


```{r (Examine Seasonally Differenced Plots)}
tsdisplay(diff(BoxCox(rent_train, lambda = 'auto'), lag=1, differences = 1)) # AR(1)
tsdisplay(diff(BoxCox(inventory_train, lambda = 0), diff=1, lag=11))  # AR(1)?

```

### Attempt to do a SVARIMA, but at the moment the p,q,P selections are mostly just off vibes
```{r (Seasonal ARIMA (SVARIMA))}
data <- as.data.frame(cbind(rent_train, inventory_train))

svarma_model <- sVARMA(data, order=c(1,1,1), sorder=c(1,1,0), s=12)
preds <- sVARMApred(svarma_model, 0, h=length(rent_test))
plot(preds$pred[,1])
plot(preds$pred[,2])
```

```{r (Check residuals)}
Box.test(svarma_model$residuals[,1], type = c("Ljung-Box"))
Box.test(svarma_model$residuals[,2], type = c("Ljung-Box"))
acf(svarma_model$residuals[,1])
acf(svarma_model$residuals[,2])
ccf(svarma_model$residuals[,2], svarma_model$residuals[,1], main="CCF of Residuals")
```


```{r}
# added - why does it blow up? incredibly sensitive to specification
svarma_model2 <- sVARMA(data, order=c(2,1,1), sorder=c(1,1,1), s=12)
preds2 <- sVARMApred(svarma_model2, 0, h=length(rent_test))
plot(preds2$pred[,1])
plot(preds2$pred[,2])
```

## Using BoxCox data does not work?
```{r}
data_box_cox <- as.data.frame(cbind(BoxCox(rent_train, lambda = lambda_rent), BoxCox(inventory_train, lambda = lambda_inventory)))

svarma_model <- sVARMA(data_box_cox, order=c(1,0,1), sorder=c(1,1,0), s=12)
```


